### ISSUE TITLE
Missing localisations for "Punctuation"

### ISSUE THREAD

**Issue by TomazErjavec** [clarinsi/mte-msd#1]
The new specs introduce Punctuation/Z for all the languages. Only 3 languages have localisations (sl, sk, uk), and we are missing the name of the category Punctuation for:
* Slovak (Radovan?)
* Ukrainian (Natalia?)

**Comment by TomazErjavec** [comment]
Found these myself, I hope they are correct:  _Interpunkcia_ and _Пунктуація_

**Comment by natko5** [comment]
@TomazErjavec The Ukrainian term is correct.

**Comment by TomazErjavec** [comment]
Thanks to both for input!
