### ISSUE TITLE
How to create a parallel corpus

### ISSUE THREAD

**Issue by stefan-it** [clarinsi/mte-msd#3]
Hi,

what I really like to do is to create a parallel corpus English <-> Macedonian of [Version 4](http://nl.ijs.si/ME/V4/). What is the prefered way to create such a corpus? Parallel corpus is meant to be for neural machine translation, so the corpus should consist of something like `1984.en` and `1984.mk`.

I thought about:

-> Creating a datastructure that holds e.g. `oana-mk.xml#Obg.1.1.1.1` (key) to its corresponding sentence (value). For that I need to parse the `oana-mk.xml` file, but I think I could just use the xslt script. But how do I use the `msd-convert2text.xsl` correctly (arguments via `xsltproc` on commandline)? This procedure is done for both English and Macedonian.

-> Then I would parse `oalg-enmk.xml` to get the sentence alignments (for that purpose I need the previously created key-value datastructure).

Is there an easier way to create a parallel corpus?

Thanks in advance :heart:

**Comment by TomazErjavec** [comment]
> Is there an easier way to create a parallel corpus [of English <-> Macedonian]? 

Yes, just download it from http://hdl.handle.net/11356/1043
